config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs

  authenticated :user do
    root 'docs#index'
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  def index
    @docs = current_user.docs.all
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc   #redirect is a new http request
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: 'button'

app/views/docs/edit.html.haml
.wrapper_with_padding

  %h1 Edit Doc

  = render 'form'

  = link_to 'Cancel', doc_path(@doc)

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - if @docs.blank?
      %h2 Create now!
      %p Start your journey with us today
      %button= link_to 'Create Doc', new_doc_path
    - else
      - @docs.each do |doc|
        %a{href: (url_for(doc))}
          .doc
            %p.title= doc.title
            %p.date= "Last updated #{time_ago_in_words(doc.updated_at)} ago"
            %p.content= truncate(doc.content, length: 50)

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 Create New Doc

  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format @doc.content

    .buttons
      = link_to 'Edit Doc', edit_doc_path(@doc), class: 'button'
      = link_to 'Delete', doc_path(@doc), method: :delete, data: { confirm: 'Sure?' }, class: 'button'

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Cabinet
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
  = csp_meta_tag
%body
  %header
    .header_inner
      = link_to 'FileCabinet', root_path, id: 'logo'

      %nav
        - if user_signed_in?
          = link_to 'New Doc', new_doc_path
          = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          = link_to 'Login', new_user_session_path

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Clutter free, simple, pratical
    %button= link_to 'Enter', new_user_registration_path
%br
#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p NYNY uses a Rack::Builder underneath to generate a proper Rack app when it is being run. Because of that, NYNY exposes the Builder's map method to allow fine grained low-level url mapping. The most common use case for that is to integrate sprockets into a NYNY app

#bottom_cta
  .wrapper
    %h2 Let's Go!
    %br
    %button= link_to 'Join now', new_user_registration_path